#include<stdio.h>
#include<sys/mman.h>
#include<stdlib.h>
#include<limits.h>
#include<semaphore.h>
#include<string.h>
#include<unistd.h>
#include<sys/wait.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<sys/types.h>
#include<stdbool.h>
